version: '3.8'

services:
  web:
    build: .
    container_name: chat-nextjs
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/chatdb
      - JWT_SECRET=my-chat-db-salt
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: chat-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
